server:
  port: 8080

spring:
  datasource:
    name: capactity
    url: jdbc:mysql://10.56.34.209:3307/pdm
    username: pdm
    password: pdm@123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    mvc:
      view:
        prefix:/
        suffix :.html
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.sinosoft.capactity.db.pojo  # 注意：对应实体类的路径
 # config-locations: classpath:mapper/config/mybatis-generator.xmlx
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


